branches:
  only:
    - 'master'
rvm:
  - ree
  - 1.9.2

env:
  - DB=sqlite3
  - DB=postgresql
  - DB=mysql

before_script: "./config/ci/before-travis.sh"

script: "export DISPLAY=:99.0 && bundle exec rake cucumber"
