branches:
  only:
    - 'master'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree

env:
  - DB=sqlite3
  - DB=postgresql
  - DB=mysql

notifications:
  recipients:
    - developer@sohbetapp.com

bundler_args:  --without linux_development mac_development

before_script: "./config/ci/before-travis.sh"

script: "DISPLAY=:99.0 bundle exec rake cucumber spec"
